
# Server configurations
server:
  port: :6060
  basepath: /pea

# Application specific configurations
application:
  name: policy-enf-agent

#options for vm generic related to HTTP Request
controlplane:
  ip: 127.0.0.1
  port: 8000
  grpc_port: 32770

